### ISSUE TITLE
drive.py initial position

### ISSUE THREAD

**Issue by RonnieFrith** [acrerd/acreroad_1420#3]
Currently the position variables self.ra and self.dec are created in the goto() method.  
https://github.com/transientlunatic/acreroad_1420/blob/master/acreroad_1420/drive.py#L201

This is a problem when I call the status() method to get the initial pointing direction.

Can these be initialised in the constructor?

**Comment by transientlunatic** [comment]
I've updated the Drive class to have the self.ra and self.dec parameters created at initialisation with a value of 0. This shouldn't be the way to do it in the long run, since we should really read the position off the drive after homing it when the connection is made.

**Comment by transientlunatic** [comment]
The Drive class now reads and parses the status output of the motor, and gets its position information from that.
